// Generated by scripts/generate-agent-docs.mjs. Edit docs/agent sources, not this output.
export const agentToolHelp = {
  connect:
    "Pair with the live browser editor. Pass its claim code once; later MCP processes can omit it and resume the saved, revocable connector. After connecting, read analog-canvas://reference/quickstart.",
  disconnect:
    "Revoke the current browser Agent session and erase this MCP host's saved connector. A fresh editor claim code is required afterwards.",
  connection_status:
    "Report runtime version, API origin and session observations. refresh:false is local-only. Attached means a browser socket exists, not verified execution readiness; unknown means the relay was not checked successfully.",
  project_cells:
    "Cloud Cell discovery/import; workspace list/activate/open/save/copy. Live tabs include unsaved work; Cloud reads saved versions. Copy reuses GUI transactions and dependencies. Details: analog-canvas://reference/mcp-tools.",
  gallery_circuits:
    "Page through every public Gallery circuit, then read one or up to 12 entries' complete Project Code and generated SPICE/Spectre netlist. Follow nextCursor until null and any remainingEntryIds until empty; pass netlistFormat:null when only Project Code is needed.",
  project_code:
    "Read or atomically replace the open Project's complete canonical Project Code. Replacement uses the live Project structure revision and the same validated, undoable commit path as the Editor's Project Code panel.",
  netlist_code:
    "Read the open Project's generated SPICE/Spectre netlist or replace its editable device names, models and values through the same planner as the Netlist panel. Use Project Code or structured circuit edits for topology and connectivity changes.",
  simulation:
    "Prepare/start/read/cancel and discover results. Run receipts never inline samples; run.details summarizes collection, diagnostics and Specs; catalog locates complete files. Capabilities default to summary; request detail:full for model facts. Prepare outer detail:full includes mappings otherwise available in preparation.json. start/read accept waitMs 0–20000; resume the same runId. Retry uncertain starts with the same requestId. One hosted run at a time or Batch. Use simulation_files sync for local results; export retries failed evidence saving without executing again.",
  simulation_files:
    "Edit native source using returned revisions; sync complete files to the local base. analysisIndex + roles:[table] selects CSV; fileIds:[] gets directory only, omitted selectors all files. prepare-plot creates editable Python/config from panels or dc/ac/tran/noise presets and optional A/B cursors; run locally with matplotlib. Never overwrites plots. download saves locally; artifact without outputPath previews. Details: analog-canvas://reference/mcp-simulation.",
  export_file:
    "Export Project or Canvas SVG/PNG/PDF to outputPath; Canvas requires documentId. For simulation data use simulation_files sync/download. simulation-plot returns SIMULATION_PLOT_RETIRED; use simulation_files prepare-plot.",
  import_file:
    "Stage a local Analog Canvas project or structural SPICE bundle, inspect/discard the candidate, or request browser approval. Staging never replaces the open project by itself.",
  get_context:
    "Compact document identity, revision, counts and diagnostic totals. Reuses the clean Snapshot; refresh:true reconciles external changes. Connect already returns bootstrap context; do not repeat this call just to confirm pairing.",
  inspect:
    "Inspect document facts, objects, nets, connectivity, diagnostics, cross-Cell traces or current-process activity. Use returned IDs and resolved pins when planning edits.",
  search:
    "Case-insensitive search, including LaTeX, over one authorized document or scope:project. Results include documentId. Reuses clean Snapshots by default and loads authorized Project documents concurrently.",
  apply_actions:
    "Apply one atomic action batch using existing planners and revision guards. Split create/wire only when new resolved pins are needed. Use the listed schema directly; native label/display semantics: analog-canvas://reference/mcp-tools.",
  advanced_transact:
    "Full transaction access, not a higher permission tier. Submit exactly one of edits, structureEdits, wireIntent, semanticIntent or command. Client supplies revisions/IDs from the clean Snapshot; stale revisions require reconciliation. Look up only unfamiliar edit kinds; reading is optional.",
  verify:
    "Force a fresh Snapshot and report revision, error/warning totals, and which object IDs changed since the cached full Snapshot. Use at a milestone, after a known external edit, or when a transaction reported STATE_CHANGED; not after every accepted edit.",
  render:
    "Render the current document to SVG and return it as an image content block (image/svg+xml) plus a compact text summary (revision, sha256, byteLength).",
  simulation_folder:
    "List/get/create/clone/rename/remove saved source experiments. Clean Project state is reused by default; refresh:true reconciles a known external change. rootDocumentId binds the drawn Cell; dut adds a text testbench using its exported name and ordered ports. Edit native source with simulation_files, not parallel JSON analyses. See analog-canvas://reference/mcp-simulation.",
  simulation_output:
    "Legacy config v1 only: manage output ASTs. Native Code uses simulation_files for saves and postprocess Python; this tool cannot add parallel JSON rules. See analog-canvas://reference/mcp-simulation. Exact expression schema: analog-canvas://contract/tools/simulation_output.",
  simulation_measurement:
    "Legacy config v1 only: manage scalar measurement rules. Native VACASK uses authored Python and report_measurement; obtain helpers with simulation authoring-help. See analog-canvas://reference/mcp-simulation.",
  simulation_device_operating_point:
    "Legacy config v1 only: select terminal-derived MOS operating-point quantities. Native Code uses module-supported saves and native OP analysis; never guess i(pin). See analog-canvas://reference/mcp-simulation.",
};
export const agentServerInstructions =
  "Analog Canvas MCP adapter over the four-operation Agent API. Connect returns context; read analog-canvas://reference/quickstart and follow only the guidance for the current task. Inspect objects when needed. Do not guess symbol IDs, pin names, or revisions.";
