// Generated by scripts/generate-agent-docs.mjs. Edit docs/agent sources, not this output.
export const agentToolHelp = {
  connect:
    "Pair with the live browser editor. Pass its claim code once; later MCP processes can omit it and resume the saved, revocable connector. After connecting, read analog-canvas://reference/quickstart.",
  disconnect:
    "Revoke the current browser Agent session and erase this MCP host's saved connector. A fresh editor claim code is required afterwards.",
  connection_status:
    "Report actual MCP runtime version and API origin. Set refresh:false for local readiness without network access. By default read lightweight Session observations without waiting for the editor: attached means a browser socket exists, not verified execution readiness; unknown means the relay could not be checked. No credentials are exposed.",
  project_cells:
    "List the signed-in user's Cloud Projects, inspect their reusable Cells and formal ports, or copy one Cell with its dependency closure into the open Project. Import uses the canonical GUI planner and one atomic Project transaction; it creates no live cross-Project reference. Ordinary sign-in, stale-revision, or compatibility failures are recoverable and do not end the Agent session.",
  simulation:
    "Prepare a saved Project folder or raw File Resource workspace; start, read, cancel and export runs or sequential batches through the shared Simulation Resource. Read the actual Profile engine. authoring-help exposes native VACASK helpers including Python reporting; do not insert ngspice meas commands into VACASK. Source code owns analyses and measurement logic. Read analog-canvas://reference/simulation-specs for engine-specific acceptance boundaries, outputData.specs or specs.json for captured verdicts, result.data/result.json for raw numbers. No automatic measurements. Large receipts use resultPreview and paged artifact access. Supply the SAME requestId for a start retry. Use simulation_files for source and ordinary Cell edits for the DUT/testbench.",
  simulation_files:
    "Edit simulation source through the canonical File Resource. list without owner recovers session workspace IDs; list/read/update use owner {kind:'session-workspace',workspaceId} or {kind:'project-folder',folderId}. read pages one path with its exact text digest. update atomically applies writes/removes/UTF-16 patches at expectedRevision; Project edits use the Project structure revision and normal history, while session files expire. Generated circuit/dependency text cannot be overwritten. Invalid authored syntax remains saveable. Project writes require the existing project.import scope, not an import approval prompt. create/discard manage session workspaces only; saved folders use Project lifecycle. artifact fetches immutable evidence; outputPath saves only artifacts locally after digest verification.",
  export_file:
    "Export the browser Project or Canvas SVG/PNG/PDF to an explicit local path. Canvas exports require documentId. Simulation results use simulation export to list artifacts, then simulation_files artifact with outputPath to save raw/CSV/Spec files after digest verification. simulation-plot is retired and returns SIMULATION_PLOT_RETIRED; plot externally from raw/CSV.",
  import_file:
    "Stage a local Analog Canvas project or structural SPICE bundle, inspect/discard the candidate, or request browser approval. Staging never replaces the open project by itself.",
  get_context:
    "Compact context for one authorized document: identity, revision, instance/net counts, and error/warning totals. Refreshes by default so concurrent human edits are visible; set refresh:false only for a deliberate cached read.",
  inspect:
    "Read a document, object, net connectivity, diagnostics, or recent MCP activity. Refreshes by default; detail:full returns the document Snapshot with appearance, formulas, interfaces, and project definitions.",
  search:
    "Case-insensitive search, including LaTeX, over one authorized document or scope:project. Results include documentId. Refreshes by default.",
  apply_actions:
    "Apply one atomic edit batch, wire, GUI-planned command, or focus operation. Includes set-model, copy, transform, align, detach-move, unplace, reset-cell, Cell creation/rename/deletion, undo/redo. Split create/wire phases. Helper handles revisions; receipts contain authoritative changes and diagnostics. Examples: analog-canvas://reference/quickstart.",
  advanced_transact:
    "Submit exactly one API transaction form: edits, structureEdits, wireIntent, semanticIntent, or command. Helper supplies revisions and IDs. Read analog-canvas://contract/advanced-edits when unfamiliar with an edit; reading is advisory, not a permission gate.",
  verify:
    "Refresh the snapshot and report revision, error/warning totals, and which object IDs changed since the cached snapshot. Use after edits or when a transaction reported STATE_CHANGED.",
  render:
    "Render the current document to SVG and return it as an image content block (image/svg+xml) plus a compact text summary (revision, sha256, byteLength).",
  simulation_folder:
    "Manage saved source experiments: list/get/create/clone/rename/remove. create writes the same native VACASK OP/AC/TRAN source template used by Code. Omit rootDocumentId for text only; rootDocumentId alone runs the drawn Cell directly. Add dut {name, ports} using the exported subcircuit name and ordered ports to start a text TB around that Cell without creating another Cell. Native parameters, analysis settings (including temperature), save and control programs are edited with simulation_files; input replacement can change bindings/dependencies. There is no parallel structured analyses authority. Updates are revision-guarded; malformed code can still be saved.",
  simulation_output:
    "Legacy version-1 experiments only: manage output ASTs in their configuration file. Native Code experiments use simulation_files to edit save selectors and postprocess Python, not .probe/let. Read simulation authoring-help for shared examples. This helper cannot downgrade native source or create parallel JSON rules.",
  simulation_measurement:
    "Legacy version-1 experiments only: manage saved per-record scalar measurements. Native VACASK experiments compute measurements in authored postprocess Python, not ngspice meas. simulation authoring-help with name embed supplies editable scalar/curve report helpers; apply source with simulation_files. This helper cannot add JSON measurement rules to native experiments.",
  simulation_device_operating_point:
    "Legacy version-1 experiments only: select MOS occurrences for terminal-derived VGS/VDS/VBS/ID. Native VACASK experiments use simulation_files for save p(instance,parameter) and analysis name op; available quantities depend on the native device module. Arbitrary terminal currents require the supported acquisition helper, not a guessed i(pin). This helper cannot add JSON selections to native experiments.",
};
export const agentServerInstructions =
  "Analog Canvas MCP adapter over the four-operation Agent API. Start with connect, read analog-canvas://reference/quickstart, then get_context. Read reference resources on demand; do not guess symbol IDs, pin names, or revisions.";
