// Generated by scripts/generate-agent-docs.mjs. Edit docs/agent sources, not this output.
export const agentToolHelp = {
  connect:
    "Pair with the live browser editor. Pass its claim code once; later MCP processes can omit it and resume the saved, revocable connector. After connecting, read analog-canvas://reference/quickstart.",
  disconnect:
    "Revoke the current browser Agent session and erase this MCP host's saved connector. A fresh editor claim code is required afterwards.",
  connection_status:
    "Report runtime version, API origin and session observations. refresh:false is local-only. Attached means a browser socket exists, not verified execution readiness; unknown means the relay was not checked successfully.",
  project_cells:
    "List Cloud Projects, inspect reusable Cell interfaces, or atomically copy a Cell and its dependency closure into the open Project. No live cross-Project link. Requires account access; see analog-canvas://reference/mcp-tools.",
  gallery_circuits:
    "Page through every public Gallery circuit, then read one or up to 12 entries' complete Project Code and generated SPICE/Spectre netlist. Follow nextCursor until null and any remainingEntryIds until empty; pass netlistFormat:null when only Project Code is needed.",
  project_code:
    "Read or atomically replace the open Project's complete canonical Project Code. Replacement uses the live Project structure revision and the same validated, undoable commit path as the Editor's Project Code panel.",
  netlist_code:
    "Read the open Project's generated SPICE/Spectre netlist or replace its editable device names, models and values through the same planner as the Netlist panel. Use Project Code or structured circuit edits for topology and connectivity changes.",
  simulation:
    "Prepare/start runs, read status, and inspect catalog metadata. history lists retained completed run identities after reconnect; catalog and sync reuse their files without restarting. Retain the SAME requestId and payload for an uncertain start retry. Native source editing remains available; authoring help is optional. outputData.specs reports verdicts; completion alone does not promise waveform capture. Prefer simulation_files sync to download complete results for local analysis. Device/vector mapping: analog-canvas://reference/mcp-simulation. Optional outer waitMs (0–20000) on start/read waits on that same run; resume via read when runId is known. One active hosted run at a time; sequence starts or use Batch.",
  simulation_files:
    "Source read/update retains owner revisions and full native editing. For small edits use replacements with path/textDigest/oldText/newText; each oldText must match exactly once in the original file. Batch edits are atomic. Success returns source.revision plus update with changed files and new digests; no mandatory reread. Listings advertise editing modes. Local action workspace opens/inspects a Project base; sync with runId downloads its catalog and complete files (fileIds selects files; [] syncs metadata only). basePath optionally chooses and remembers a local directory; otherwise one is created automatically. download with artifactId saves locally by default; outputPath overrides its location. artifact without outputPath is text preview only. See analog-canvas://reference/mcp-simulation.",
  export_file:
    "Export the browser Project or Canvas SVG/PNG/PDF to an explicit local path. Canvas exports require documentId. Simulation results use returned run artifact references (or simulation export when an inventory is needed), then simulation_files artifact with outputPath to save raw/CSV/Spec files after digest verification. simulation-plot is retired and returns SIMULATION_PLOT_RETIRED; plot externally from raw/CSV.",
  import_file:
    "Stage a local Analog Canvas project or structural SPICE bundle, inspect/discard the candidate, or request browser approval. Staging never replaces the open project by itself.",
  get_context:
    "Compact context for one authorized document: identity, revision, instance/net counts, and error/warning totals. Refreshes by default so concurrent human edits are visible; set refresh:false only for a deliberate cached read.",
  inspect:
    "Read a document, object, net connectivity, diagnostics, or recent MCP activity. Refreshes by default; detail:full returns the document Snapshot with appearance, formulas, interfaces, and project definitions.",
  search:
    "Case-insensitive search, including LaTeX, over one authorized document or scope:project. Results include documentId. Refreshes by default.",
  apply_actions:
    "Apply one atomic batch, wire, GUI-planned command or focus operation. Client plans edits and supplies revisions; split create/wire phases for resolved pins. Actions and native labels/displays: analog-canvas://reference/mcp-tools.",
  advanced_transact:
    "Submit exactly one of edits, structureEdits, wireIntent, semanticIntent or command. Client plans the transaction and supplies revisions/IDs; dryRun is optional. Read analog-canvas://contract/edits/{kind} for one edit schema; full offline schema: analog-canvas://contract/advanced-edits. Reading is advisory.",
  verify:
    "Refresh the snapshot and report revision, error/warning totals, and which object IDs changed since the cached snapshot. Use after edits or when a transaction reported STATE_CHANGED.",
  render:
    "Render the current document to SVG and return it as an image content block (image/svg+xml) plus a compact text summary (revision, sha256, byteLength).",
  simulation_folder:
    "List/get/create/clone/rename/remove saved source experiments. rootDocumentId binds the drawn Cell; dut adds a text testbench using its exported name and ordered ports. Edit native source with simulation_files, not parallel JSON analyses. See analog-canvas://reference/mcp-simulation.",
  simulation_output:
    "Legacy config v1 only: manage output ASTs. Native Code uses simulation_files for saves and postprocess Python; this tool cannot add parallel JSON rules. See analog-canvas://reference/mcp-simulation. Exact expression schema: analog-canvas://contract/tools/simulation_output.",
  simulation_measurement:
    "Legacy config v1 only: manage scalar measurement rules. Native VACASK uses authored Python and report_measurement; obtain helpers with simulation authoring-help. See analog-canvas://reference/mcp-simulation.",
  simulation_device_operating_point:
    "Legacy config v1 only: select terminal-derived MOS operating-point quantities. Native Code uses module-supported saves and native OP analysis; never guess i(pin). See analog-canvas://reference/mcp-simulation.",
};
export const agentServerInstructions =
  "Analog Canvas MCP adapter over the four-operation Agent API. Connect returns context; read analog-canvas://reference/quickstart and follow only the guidance for the current task. Inspect objects when needed. Do not guess symbol IDs, pin names, or revisions.";
