import { describe, expect, it, vi } from "vitest";
import { parseProject, serializeProject } from "@icm/project-protocol";
import { generateCircuitSource } from "@icm/netlist";
import { SimulationFiles, sha256 } from "@icm/simulation-service/files";
import ota from "../../examples/five-transistor-ota-sky130.icproj.json";
import { EditorDocumentController } from "../../document/document-controller";
import { createSimulationProjectFileHost } from "./project-file-host";

function fixture(actor: "human" | "agent" = "human") {
  const controller = new EditorDocumentController(
    parseProject(JSON.stringify(ota)),
  );
  const dispatch = vi.fn(
    (
      request: Parameters<
        EditorDocumentController["dispatchProjectTransaction"]
      >[0],
    ) => controller.dispatchProjectTransaction(request),
  );
  const host = createSimulationProjectFileHost({
    getProject: () => controller.project,
    getProjectSessionId: () => controller.projectSessionId,
    dispatch,
    actor: { kind: actor, id: actor },
  });
  const files = new SimulationFiles(Date.now, host);
  const setup = controller.project.simulationSetups[0]!;
  const generated = generateCircuitSource(
    controller.project,
    setup.input.circuitBindings[0]!,
  );
  if (!generated.ok) throw Error(JSON.stringify(generated.diagnostics));
  const source = generated.source;
  const span = source.parameters.find((span) => span.parameter === "w")!;
  const text =
    source.text.slice(0, span.startOffset) +
    "8" +
    source.text.slice(span.endOffset);
  return {
    controller,
    dispatch,
    files,
    setup,
    source,
    span,
    text,
    owner: { kind: "project-setup" as const, setupId: setup.id },
  };
}
describe("shared human/Agent generated Circuit File Resource", () => {
  it.each(["human", "agent"] as const)(
    "commits source and mapped sizes atomically with normal undo/redo (%s)",
    async (actor) => {
      const f = fixture(actor),
        before = f.controller.project;
      const read = await f.files.handle({
        action: "read",
        owner: f.owner,
        path: f.source.binding.path,
      });
      expect(read).toMatchObject({
        ok: true,
        text: f.source.text,
        instances: f.source.instances,
        editableParameters: expect.arrayContaining([
          expect.objectContaining({ parameter: "w" }),
        ]),
      });
      const written = await f.files.handle({
        action: "update",
        owner: f.owner,
        expectedRevision: before.structureRevision,
        writes: [
          {
            path: f.setup.input.entry,
            text: "* 🧪\r\nunfinished code is saveable\r\n",
          },
        ],
        circuitEdits: [
          {
            path: f.source.binding.path,
            textDigest: await sha256(f.source.text),
            text: f.text,
          },
        ],
      });
      expect(written).toMatchObject({
        ok: true,
        source: { revision: before.structureRevision + 1 },
      });
      expect(f.dispatch).toHaveBeenCalledTimes(1);
      const after = f.controller.project;
      expect(
        after.documents
          .find((d) => d.id === f.span.documentId)!
          .instances.find((i) => i.id === f.span.instanceId)!.netlist!
          .parameters.w,
      ).not.toBe(
        before.documents
          .find((d) => d.id === f.span.documentId)!
          .instances.find((i) => i.id === f.span.instanceId)!.netlist!
          .parameters.w,
      );
      expect(parseProject(serializeProject(after))).toEqual(after);
      f.controller.transact([{ kind: "undo" }]);
      expect(
        f.controller.project.documents.map(
          ({ revision, ...content }) => content,
        ),
      ).toEqual(before.documents.map(({ revision, ...content }) => content));
      expect(f.controller.project.simulationSetups).toEqual(
        before.simulationSetups,
      );
      f.controller.transact([{ kind: "redo" }]);
      expect(f.controller.project.documents.map((d) => d.instances)).toEqual(
        after.documents.map((d) => d.instances),
      );
      expect(f.controller.project.simulationSetups).toEqual(
        after.simulationSetups,
      );
    },
  );
  it("rejects topology and stale generated bytes without applying any authored half", async () => {
    const f = fixture(),
      before = f.controller.project;
    for (const edit of [
      {
        textDigest: await sha256(f.source.text),
        text: f.text + "\nRextra a 0 1k",
      },
      { textDigest: "a".repeat(64), text: f.text },
    ]) {
      const result = await f.files.handle({
        action: "update",
        owner: f.owner,
        expectedRevision: before.structureRevision,
        writes: [
          {
            path: f.setup.input.configPath,
            text: "invalid JSON can be saved, but not half a rejected transaction",
          },
        ],
        circuitEdits: [{ path: f.source.binding.path, ...edit }],
      });
      expect(result.ok).toBe(false);
      expect(f.controller.project).toBe(before);
    }
    expect(f.dispatch).not.toHaveBeenCalled();
  });
  it("detects revision changes and allows repair without losing the session", async () => {
    const f = fixture(),
      revision = f.controller.project.structureRevision;
    const write = (expectedRevision: number) =>
      f.files.handle({
        action: "update",
        owner: f.owner,
        expectedRevision,
        writes: [{ path: f.setup.input.configPath, text: "{" }],
      });
    expect(
      f.controller.dispatchProjectTransaction({
        transactionId: "concurrent",
        projectId: f.controller.project.id,
        expectedStructureRevision: revision,
        actor: { kind: "human", id: "human" },
        edits: [{ kind: "rename_project", name: "Changed elsewhere" }],
      }).ok,
    ).toBe(true);
    expect(await write(revision)).toMatchObject({
      ok: false,
      error: { code: "PROJECT_REVISION_CONFLICT" },
    });
    expect(await write(f.controller.project.structureRevision)).toMatchObject({
      ok: true,
    });
    expect(
      parseProject(
        serializeProject(f.controller.project),
      ).simulationSetups[0]!.input.files.find(
        (file) => file.path === f.setup.input.configPath,
      )!.text,
    ).toBe("{");
  });
});
