// Generated by scripts/generate-razavi-symbol-catalog.mjs. Do not edit.
import type { SymbolDefinition } from "./schema.js";
import type {
  RazaviSemanticPrimitiveEntry,
  RazaviSymbolCatalogEntry,
} from "./razavi-catalog.js";

export const razaviSymbolCatalogIdentity = {
  schemaVersion: 2,
  id: "razavi-symbols",
  version: 1,
} as const;

export const razaviSymbolCatalogEntries: readonly RazaviSymbolCatalogEntry[] = [
  {
    symbolId: "capacitor",
    name: "Capacitor",
    category: "passive",
    reviewStatus: "reviewed",
    pinOrder: ["1", "2"],
    palette: true,
    automaticMappings: ["spice:C"],
    assetPath: "capacitor.symbol.json",
    assetHash:
      "6ccdd4cdcbbd95bd10c0a59f83edd58c1b7ace5fca39a7a485b45e7dca3fe6b2",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/capacitor-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/capacitor-geometry.json",
    },
  },
  {
    symbolId: "closed-switch",
    name: "Closed Switch",
    category: "switch",
    reviewStatus: "reviewed",
    pinOrder: ["1", "2"],
    palette: true,
    automaticMappings: [],
    manualOnlyReason:
      "Two-terminal Razavi switch; SPICE S has a four-terminal control contract.",
    assetPath: "closed-switch.symbol.json",
    assetHash:
      "b28f94edb706cc30d505eb0e26cdbb98e815c8c5a2838312df0f148aa6ed525a",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/closed-switch-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/closed-switch-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/common-symbol-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/closed-switch-vector-source.json",
      converterPath: "scripts/generate-razavi-common-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "current-source",
    name: "Independent Current Source",
    category: "source",
    reviewStatus: "reviewed",
    pinOrder: ["+", "-"],
    palette: true,
    automaticMappings: ["spice:I"],
    assetPath: "current-source.symbol.json",
    assetHash:
      "fa00a8c4aac387e2d5531d560dabf0897df079fdbcb3cef9823f67d6a564e796",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/current-port-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/current-port-geometry.json",
    },
    generation: {
      kind: "razavi-raster-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      converterPath: "scripts/generate-razavi-peripheral-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "diode",
    name: "Diode",
    category: "passive",
    reviewStatus: "reviewed",
    pinOrder: ["A", "K"],
    palette: true,
    automaticMappings: ["spice:D"],
    assetPath: "diode.symbol.json",
    assetHash:
      "9f7b396145d285f43d3a88ff74ab75ebf9177b0bb32223dd3c9f03e353167899",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/diode-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/diode-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/common-symbol-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/diode-vector-source.json",
      converterPath: "scripts/generate-razavi-common-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "ground",
    name: "Ground",
    category: "power",
    reviewStatus: "reviewed",
    pinOrder: ["0"],
    palette: true,
    automaticMappings: [],
    assetPath: "ground.symbol.json",
    assetHash:
      "b2ca65ec6b08eb1395070f3442dac5374d62472ae02789121466767bd09d6a1a",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/peripheral-geometry.json",
    },
    generation: {
      kind: "razavi-raster-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      converterPath: "scripts/generate-razavi-peripheral-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "ideal-switch",
    name: "Ideal Switch",
    category: "switch",
    reviewStatus: "reviewed",
    pinOrder: ["1", "2"],
    palette: true,
    automaticMappings: [],
    manualOnlyReason:
      "Two-terminal Razavi switch; SPICE S has a four-terminal control contract.",
    assetPath: "ideal-switch.symbol.json",
    assetHash:
      "953a05399eae5ecbedf4f237020bac864f46b94621082065e60f555226d0bce2",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/ideal-switch-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/ideal-switch-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/common-symbol-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/ideal-switch-vector-source.json",
      converterPath: "scripts/generate-razavi-common-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "inductor",
    name: "Inductor",
    category: "passive",
    reviewStatus: "reviewed",
    pinOrder: ["1", "2"],
    palette: true,
    automaticMappings: ["spice:L"],
    assetPath: "inductor.symbol.json",
    assetHash:
      "b281e6f3fcca59eb84a5dfc1f9b9fd93a29bef226cc5b7113a3fd91f3c10d55e",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/inductor-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/inductor-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/inductor-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/inductor-vector-source.json",
      converterPath: "scripts/generate-razavi-inductor-asset.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "nmos",
    name: "NMOS",
    category: "transistor",
    reviewStatus: "reviewed",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/mos-geometry.json",
    },
    pinOrder: ["D", "G", "S", "B"],
    palette: true,
    automaticMappings: ["spice:M:nmos", "pdk:model-type:nmos"],
    assetPath: "nmos.symbol.json",
    assetHash:
      "ed4a97e6d6192f83e24a20d29a311858bfe45d19b1b3810cbc3af903f5b99b87",
  },
  {
    symbolId: "npn",
    name: "NPN Bipolar Transistor",
    category: "transistor",
    reviewStatus: "reviewed",
    pinOrder: ["C", "B", "E"],
    palette: true,
    automaticMappings: ["spice:Q:npn", "pdk:model-type:npn"],
    assetPath: "npn.symbol.json",
    assetHash:
      "2f16db20b1a6766f55d5f66e493e2e9c6230dd99052a34b65ebf254b9be57978",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/npn-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/npn-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/common-symbol-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/npn-vector-source.json",
      converterPath: "scripts/generate-razavi-common-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "opamp",
    name: "Operational Amplifier",
    category: "analog-block",
    reviewStatus: "reviewed",
    pinOrder: ["IN+", "IN-", "OUT"],
    palette: true,
    automaticMappings: [],
    manualOnlyReason:
      "Three-terminal textbook op-amp; SPICE subcircuit pin and supply contracts require an explicit PDK mapping.",
    assetPath: "opamp.symbol.json",
    assetHash:
      "2e248f3880f7d03ccc2e15649f7053751cc5312cf915a251fcd0e07da35de16a",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/opamp-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/opamp-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/opamp-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/opamp-vector-source.json",
      converterPath: "scripts/generate-razavi-opamp-asset.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "pmos",
    name: "PMOS",
    category: "transistor",
    reviewStatus: "reviewed",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/mos-geometry.json",
    },
    pinOrder: ["D", "G", "S", "B"],
    palette: true,
    automaticMappings: ["spice:M:pmos", "pdk:model-type:pmos"],
    assetPath: "pmos.symbol.json",
    assetHash:
      "72080a26eb50b6c46ea14faa57cc1c468361c26731a1817cad467e620bb8620a",
  },
  {
    symbolId: "pnp",
    name: "PNP Bipolar Transistor",
    category: "transistor",
    reviewStatus: "reviewed",
    pinOrder: ["C", "B", "E"],
    palette: true,
    automaticMappings: ["spice:Q:pnp", "pdk:model-type:pnp"],
    assetPath: "pnp.symbol.json",
    assetHash:
      "831c12896ded98badf9e75be73d1965e760044c46dcfb03dd7a0cfb598abf4fc",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/pnp-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/pnp-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/common-symbol-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/pnp-vector-source.json",
      converterPath: "scripts/generate-razavi-common-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "port",
    name: "Port",
    category: "interface",
    reviewStatus: "reviewed",
    pinOrder: ["P"],
    palette: true,
    automaticMappings: [],
    assetPath: "port.symbol.json",
    assetHash:
      "4d17eea1df130c008fa194c65012a9d6893c7245b7d4bb78b4f37e0187c569ea",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/current-port-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/current-port-geometry.json",
    },
  },
  {
    symbolId: "port-filled",
    name: "Filled Port",
    category: "interface",
    reviewStatus: "reviewed",
    pinOrder: ["P"],
    palette: true,
    automaticMappings: [],
    manualOnlyReason:
      "Explicit solid endpoint style; no automatic SPICE mapping.",
    assetPath: "port-filled.symbol.json",
    assetHash:
      "fa0159b800b6df515bfd876704b1cd448de280b63fc48df14221dcc5bb89bbcb",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/current-port-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/current-port-geometry.json",
    },
  },
  {
    symbolId: "resistor",
    name: "Resistor",
    category: "passive",
    reviewStatus: "reviewed",
    pinOrder: ["1", "2"],
    palette: true,
    automaticMappings: ["spice:R"],
    assetPath: "resistor.symbol.json",
    assetHash:
      "28c1b0fcbd541685dec951e05b1a1f1fe71a6aabf572c5b706143b377b7677c1",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/passive-geometry.json",
    },
  },
  {
    symbolId: "voltage-amplifier",
    name: "Voltage Amplifier",
    category: "analog-block",
    reviewStatus: "reviewed",
    pinOrder: ["IN", "OUT"],
    palette: true,
    automaticMappings: [],
    manualOnlyReason:
      "Textbook gain block has implicit reference nodes and no exact primitive SPICE terminal contract.",
    assetPath: "voltage-amplifier.symbol.json",
    assetHash:
      "538411b2fc3df120f910c47c92502b1b4bdefef52f1296170167180c61109816",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/voltage-amplifier-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/voltage-amplifier-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/common-symbol-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/voltage-amplifier-vector-source.json",
      converterPath: "scripts/generate-razavi-common-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "voltage-source",
    name: "Independent Voltage Source",
    category: "source",
    reviewStatus: "reviewed",
    pinOrder: ["+", "-"],
    palette: true,
    automaticMappings: ["spice:V"],
    assetPath: "voltage-source.symbol.json",
    assetHash:
      "9f295fd28893155c8e3e73f26fd5f858f99a54b77b1917720ee2fbb02fb2942c",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/peripheral-geometry.json",
    },
    generation: {
      kind: "razavi-raster-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      converterPath: "scripts/generate-razavi-peripheral-assets.mjs",
      converterVersion: 1,
    },
  },
];

export const razaviSemanticPrimitives: readonly RazaviSemanticPrimitiveEntry[] =
  [
    {
      id: "junction-dot",
      disposition: "semantic-primitive",
      geometry: {
        kind: "circle",
        sourceDiameterIU: 0.0787401574803157,
        fill: "foreground",
        stroke: "none",
      },
      runtimeOwner: "presentation.nodes.junction",
    },
  ];

export const razaviCatalogSymbols: readonly SymbolDefinition[] = [
  {
    schemaVersion: 1,
    id: "capacitor",
    name: "Capacitor",
    viewBox: {
      x: -12,
      y: -24,
      width: 24,
      height: 48,
    },
    pins: [
      {
        name: "1",
        role: "passive",
        at: {
          x: 0,
          y: -20,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "2",
        role: "passive",
        at: {
          x: 0,
          y: 20,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: 8.05064,
          y: -3.233605,
        },
        to: {
          x: -8.05064,
          y: -3.233605,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 8.05064,
          y: 3.233605,
        },
        to: {
          x: -8.05064,
          y: 3.233605,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: -3.233605,
        },
        to: {
          x: 0,
          y: -20,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: 3.233605,
        },
        to: {
          x: 0,
          y: 20,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
  },
  {
    schemaVersion: 1,
    id: "closed-switch",
    name: "Closed Switch",
    viewBox: {
      x: -34,
      y: -12,
      width: 68,
      height: 24,
    },
    pins: [
      {
        name: "1",
        role: "passive",
        at: {
          x: -30,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "2",
        role: "passive",
        at: {
          x: 30,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -30,
          y: 0,
        },
        to: {
          x: -13.562064,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "circle",
        center: {
          x: -10.36318,
          y: 0,
        },
        radius: 3.198884,
        fill: "none",
        stroke: "foreground",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -7.186611,
          y: -1.496234,
        },
        to: {
          x: 13.608926,
          y: -4.694003,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "circle",
        center: {
          x: 10.36318,
          y: 0,
        },
        radius: 3.198884,
        fill: "none",
        stroke: "foreground",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 13.562064,
          y: 0,
        },
        to: {
          x: 30,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
  },
  {
    schemaVersion: 1,
    id: "current-source",
    name: "Independent Current Source",
    viewBox: {
      x: -15,
      y: -24,
      width: 30,
      height: 48,
    },
    pins: [
      {
        name: "+",
        role: "positive",
        at: {
          x: 0,
          y: -20,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "-",
        role: "negative",
        at: {
          x: 0,
          y: 20,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "circle",
        center: {
          x: 0,
          y: 0,
        },
        radius: 10.755814,
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: -6.976744,
        },
        to: {
          x: 0,
          y: -2.325581,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: 0,
            y: 6.976744,
          },
          {
            x: -4.651163,
            y: -2.325581,
          },
          {
            x: 4.651163,
            y: -2.325581,
          },
        ],
        fill: "foreground",
        stroke: "none",
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: -10.755814,
        },
        to: {
          x: 0,
          y: -20,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: 10.755814,
        },
        to: {
          x: 0,
          y: 20,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
  },
  {
    schemaVersion: 1,
    id: "diode",
    name: "Diode",
    viewBox: {
      x: -24,
      y: -10,
      width: 48,
      height: 20,
    },
    pins: [
      {
        name: "A",
        role: "anode",
        at: {
          x: -20,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "K",
        role: "cathode",
        at: {
          x: 20,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -20,
          y: 0,
        },
        to: {
          x: -8.333334,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: -8.333334,
            y: -6.75,
          },
          {
            x: -8.333334,
            y: 6.75,
          },
          {
            x: 5.833334,
            y: 0,
          },
        ],
        fill: "none",
        stroke: "foreground",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 6.666666,
          y: -7.333334,
        },
        to: {
          x: 6.666666,
          y: 7.333334,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 6.666666,
          y: 0,
        },
        to: {
          x: 20,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
  },
  {
    schemaVersion: 1,
    id: "ground",
    name: "Ground",
    viewBox: {
      x: -12,
      y: -14,
      width: 24,
      height: 31,
    },
    pins: [
      {
        name: "0",
        role: "ground",
        at: {
          x: 0,
          y: -10,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: 0,
          y: -10,
        },
        to: {
          x: 0,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -6.395349,
          y: 0,
        },
        to: {
          x: 6.395349,
          y: 0,
        },
        style: {
          strokeRole: "ground",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -4.069767,
          y: 5.813953,
        },
        to: {
          x: 4.069767,
          y: 5.813953,
        },
        style: {
          strokeRole: "ground",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -2.325581,
          y: 11.046512,
        },
        to: {
          x: 2.325581,
          y: 11.046512,
        },
        style: {
          strokeRole: "ground",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
    labelVisibility: "hidden",
  },
  {
    schemaVersion: 1,
    id: "ideal-switch",
    name: "Open Switch",
    viewBox: {
      x: -34,
      y: -18,
      width: 68,
      height: 30,
    },
    pins: [
      {
        name: "1",
        role: "passive",
        at: {
          x: -30,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "2",
        role: "passive",
        at: {
          x: 30,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -30,
          y: 0,
        },
        to: {
          x: -12.726917,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "circle",
        center: {
          x: -9.524128,
          y: -0.020084,
        },
        radius: 3.202789,
        fill: "none",
        stroke: "foreground",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -6.953731,
          y: -2.417959,
        },
        to: {
          x: 6.405579,
          y: -12.806695,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "circle",
        center: {
          x: 11.201116,
          y: -0.020084,
        },
        radius: 3.202232,
        fill: "none",
        stroke: "foreground",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 14.403348,
          y: 0,
        },
        to: {
          x: 30,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
  },
  {
    schemaVersion: 1,
    id: "inductor",
    name: "Inductor",
    viewBox: {
      x: -15,
      y: -32,
      width: 30,
      height: 64,
    },
    pins: [
      {
        name: "1",
        role: "passive",
        at: {
          x: 0,
          y: -30,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "2",
        role: "passive",
        at: {
          x: 0,
          y: 30,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "path",
        data: "M 0 -30 L 0 -29.243 C 0 -29.243 0 -29.243 0 -27.3261 C 0 -25.4114 0 -21.5777 0 -19.663 C 0 -17.7462 0 -17.7462 0 -17.7462 C 0 -17.7462 0 -17.7462 1.86778 -17.3623 C 3.73333 -16.9785 7.46443 -16.2131 9.28089 -14.6801 C 11.0974 -13.147 10.9969 -10.8485 7.26583 -9.31325 C 3.5325 -7.78019 -3.83152 -7.01478 -7.51353 -8.16402 C -11.1955 -9.31325 -11.1955 -12.3816 -7.46443 -13.0801 C -3.7311 -13.7808 3.73333 -12.1138 7.53138 -9.58103 C 11.3317 -7.04826 11.4633 -3.64965 7.73222 -1.4159 C 3.99888 0.815621 -3.59944 1.88229 -7.39749 0.882566 C -11.1955 -0.117155 -11.1955 -3.18326 -7.39749 -3.94868 C -3.59944 -4.71632 3.99888 -3.18326 7.69874 -0.683961 C 11.3986 1.81534 11.1978 5.28089 7.39749 7.58159 C 3.59944 9.88006 -3.79805 11.0137 -7.49791 10.0474 C -11.1955 9.08117 -11.1955 6.01506 -7.49791 5.06443 C -3.79805 4.11604 3.59944 5.28089 7.33277 7.19777 C 11.0639 9.11464 11.1308 11.7813 9.29875 13.4974 C 7.46443 15.2134 3.73333 15.9788 1.86778 16.3626 C 0 16.7464 0 16.7464 0 16.7464 C 0 16.7464 0 16.7464 0 18.8285 C 0 20.9105 0 25.0767 0 27.1609 C 0 29.243 0 29.243 0 29.243 L 0 30",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "round",
        },
      },
    ],
    variants: [],
  },
  {
    schemaVersion: 1,
    id: "nmos",
    name: "NMOS",
    viewBox: {
      x: -24,
      y: -24,
      width: 48,
      height: 48,
    },
    pins: [
      {
        name: "D",
        role: "drain",
        at: {
          x: 10,
          y: -20,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "G",
        role: "gate",
        at: {
          x: -20,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "S",
        role: "source",
        at: {
          x: 10,
          y: 20,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "B",
        role: "bulk",
        at: {
          x: 20,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "polyline",
        points: [
          {
            x: -4.244186,
            y: -6.976744,
          },
          {
            x: 10,
            y: -6.976744,
          },
          {
            x: 10,
            y: -20,
          },
        ],
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polyline",
        points: [
          {
            x: -4.244186,
            y: 6.976744,
          },
          {
            x: 10,
            y: 6.976744,
          },
          {
            x: 10,
            y: 20,
          },
        ],
        part: "source-arrow-host",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: -11.802326,
            y: -9.593023,
          },
          {
            x: -11.802326,
            y: 9.593023,
          },
          {
            x: -8.895349,
            y: 9.593023,
          },
          {
            x: -8.895349,
            y: -9.593023,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "gate-bar",
      },
      {
        kind: "polygon",
        points: [
          {
            x: -6.569767,
            y: -12.5,
          },
          {
            x: -6.569767,
            y: 12.5,
          },
          {
            x: -3.662791,
            y: 12.5,
          },
          {
            x: -3.662791,
            y: -12.5,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "gate-bar",
      },
      {
        kind: "line",
        from: {
          x: -8.895349,
          y: 0,
        },
        to: {
          x: -20,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -3.662791,
          y: 0,
        },
        to: {
          x: 10,
          y: 0,
        },
        part: "bulk-lead",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 16.395349,
          y: 0,
        },
        to: {
          x: 20,
          y: 0,
        },
        part: "bulk-lead",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: 10,
            y: 0,
          },
          {
            x: 16.395349,
            y: -3.488372,
          },
          {
            x: 16.395349,
            y: 3.488372,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "bulk-lead",
      },
    ],
    variants: [
      {
        id: "textbook-3terminal",
        hiddenPinNames: ["B"],
        auxiliaryPins: [
          {
            name: "B",
            at: {
              x: -4,
              y: 0,
            },
            direction: "east",
          },
        ],
        hiddenPrimitiveParts: ["bulk-lead", "source-arrow-host"],
        additionalPrimitives: [
          {
            kind: "polyline",
            points: [
              {
                x: -3.662791,
                y: 6.976744,
              },
              {
                x: 10,
                y: 6.976744,
              },
              {
                x: 10,
                y: 20,
              },
            ],
            part: "source-arrow",
            style: {
              strokeRole: "normal",
              lineCap: "butt",
              lineJoin: "miter",
            },
          },
          {
            kind: "polygon",
            points: [
              {
                x: 10.581395,
                y: 6.976744,
              },
              {
                x: 1.27907,
                y: 2.906977,
              },
              {
                x: 1.27907,
                y: 11.046512,
              },
            ],
            fill: "foreground",
            stroke: "none",
            part: "source-arrow",
          },
        ],
      },
    ],
    defaultVariantId: "textbook-3terminal",
  },
  {
    schemaVersion: 1,
    id: "npn",
    name: "NPN Bipolar Transistor",
    viewBox: {
      x: -44,
      y: -34,
      width: 52,
      height: 68,
    },
    pins: [
      {
        name: "C",
        role: "collector",
        at: {
          x: 0,
          y: -30,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "B",
        role: "base",
        at: {
          x: -40,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "E",
        role: "emitter",
        at: {
          x: 0,
          y: 30,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -40,
          y: 0,
        },
        to: {
          x: -16.868887,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -16.868887,
          y: -13.345607,
        },
        to: {
          x: -16.868887,
          y: 13.32954,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polyline",
        points: [
          {
            x: -16.868887,
            y: -6.401526,
          },
          {
            x: 0,
            y: -13.379732,
          },
          {
            x: 0,
            y: -30,
          },
        ],
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -16.868887,
          y: 6.403673,
        },
        to: {
          x: -7.30071,
          y: 10.358712,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polyline",
        points: [
          {
            x: -0.936056,
            y: 12.990761,
          },
          {
            x: 0,
            y: 13.377859,
          },
          {
            x: 0,
            y: 30,
          },
        ],
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: -6.635095,
            y: 6.792086,
          },
          {
            x: -9.952643,
            y: 13.377859,
          },
          {
            x: 0,
            y: 13.377859,
          },
        ],
        fill: "foreground",
        stroke: "none",
      },
    ],
    variants: [],
  },
  {
    schemaVersion: 1,
    id: "opamp",
    name: "Operational Amplifier",
    viewBox: {
      x: -54,
      y: -28,
      width: 98,
      height: 56,
    },
    pins: [
      {
        name: "IN+",
        role: "non-inverting-input",
        at: {
          x: -50,
          y: 10,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 20,
        },
      },
      {
        name: "IN-",
        role: "inverting-input",
        at: {
          x: -50,
          y: -10,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 20,
        },
      },
      {
        name: "OUT",
        role: "output",
        at: {
          x: 40,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 20,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -50,
          y: -10,
        },
        to: {
          x: -26.952962,
          y: -10,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -50,
          y: 10,
        },
        to: {
          x: -26.797909,
          y: 10,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 23.202091,
          y: 0,
        },
        to: {
          x: 40,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "path",
        data: "M -26.7979 -24.9983 L -26.7979 25 L 23.2021 0 Z",
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
          miterLimit: 4,
        },
      },
      {
        kind: "line",
        from: {
          x: -18.047038,
          y: 8.749129,
        },
        to: {
          x: -18.047038,
          y: 16.249129,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -21.796167,
          y: 12.5,
        },
        to: {
          x: -14.296167,
          y: 12.5,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -21.796167,
          y: -12.5,
        },
        to: {
          x: -14.296167,
          y: -12.5,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
  },
  {
    schemaVersion: 1,
    id: "pmos",
    name: "PMOS",
    viewBox: {
      x: -24,
      y: -24,
      width: 48,
      height: 48,
    },
    pins: [
      {
        name: "D",
        role: "drain",
        at: {
          x: 10,
          y: 20,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "G",
        role: "gate",
        at: {
          x: -20,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "S",
        role: "source",
        at: {
          x: 10,
          y: -20,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "B",
        role: "bulk",
        at: {
          x: 20,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "polyline",
        points: [
          {
            x: -4.244186,
            y: 6.976744,
          },
          {
            x: 10,
            y: 6.976744,
          },
          {
            x: 10,
            y: 20,
          },
        ],
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polyline",
        points: [
          {
            x: -4.244186,
            y: -6.976744,
          },
          {
            x: 10,
            y: -6.976744,
          },
          {
            x: 10,
            y: -20,
          },
        ],
        part: "source-arrow-host",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: -11.802326,
            y: -9.593023,
          },
          {
            x: -11.802326,
            y: 9.593023,
          },
          {
            x: -8.895349,
            y: 9.593023,
          },
          {
            x: -8.895349,
            y: -9.593023,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "gate-bar",
      },
      {
        kind: "polygon",
        points: [
          {
            x: -6.569767,
            y: -12.5,
          },
          {
            x: -6.569767,
            y: 12.5,
          },
          {
            x: -3.662791,
            y: 12.5,
          },
          {
            x: -3.662791,
            y: -12.5,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "gate-bar",
      },
      {
        kind: "line",
        from: {
          x: -8.895349,
          y: 0,
        },
        to: {
          x: -20,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -3.662791,
          y: 0,
        },
        to: {
          x: 13.604651,
          y: 0,
        },
        part: "bulk-lead",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: 20,
            y: 0,
          },
          {
            x: 13.604651,
            y: -3.77907,
          },
          {
            x: 13.604651,
            y: 3.77907,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "bulk-lead",
      },
    ],
    variants: [
      {
        id: "textbook-3terminal",
        hiddenPinNames: ["B"],
        auxiliaryPins: [
          {
            name: "B",
            at: {
              x: -4,
              y: 0,
            },
            direction: "east",
          },
        ],
        hiddenPrimitiveParts: ["bulk-lead", "source-arrow-host"],
        additionalPrimitives: [
          {
            kind: "polyline",
            points: [
              {
                x: 5.639535,
                y: -7.122093,
              },
              {
                x: 10,
                y: -7.122093,
              },
              {
                x: 10,
                y: -20,
              },
            ],
            part: "source-arrow",
            style: {
              strokeRole: "normal",
              lineCap: "butt",
              lineJoin: "miter",
            },
          },
          {
            kind: "polygon",
            points: [
              {
                x: -3.662791,
                y: -7.122093,
              },
              {
                x: 5.639535,
                y: -11.19186,
              },
              {
                x: 5.639535,
                y: -3.052326,
              },
            ],
            fill: "foreground",
            stroke: "none",
            part: "source-arrow",
          },
        ],
      },
    ],
    defaultVariantId: "textbook-3terminal",
  },
  {
    schemaVersion: 1,
    id: "pnp",
    name: "PNP Bipolar Transistor",
    viewBox: {
      x: -44,
      y: -34,
      width: 52,
      height: 68,
    },
    pins: [
      {
        name: "C",
        role: "collector",
        at: {
          x: 0,
          y: 30,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "B",
        role: "base",
        at: {
          x: -40,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "E",
        role: "emitter",
        at: {
          x: 0,
          y: -30,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -40,
          y: 0,
        },
        to: {
          x: -16.868887,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -16.868887,
          y: -13.333557,
        },
        to: {
          x: -16.868887,
          y: 13.34159,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polyline",
        points: [
          {
            x: -8.575018,
            y: -9.694413,
          },
          {
            x: 0,
            y: -13.379732,
          },
          {
            x: 0,
            y: -30,
          },
        ],
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polyline",
        points: [
          {
            x: -16.868887,
            y: 6.401526,
          },
          {
            x: 0,
            y: 13.377859,
          },
          {
            x: 0,
            y: 30,
          },
        ],
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: -10.233792,
            y: -12.987299,
          },
          {
            x: -6.916244,
            y: -6.401526,
          },
          {
            x: -16.868887,
            y: -6.401526,
          },
        ],
        fill: "foreground",
        stroke: "none",
      },
    ],
    variants: [],
  },
  {
    schemaVersion: 1,
    id: "port",
    name: "Port",
    viewBox: {
      x: -14,
      y: -7,
      width: 28,
      height: 14,
    },
    pins: [
      {
        name: "P",
        role: "port",
        at: {
          x: 10,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "circle",
        center: {
          x: -7.086614,
          y: 0,
        },
        radius: 2.47907,
        fill: "none",
        stroke: "foreground",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 10,
          y: 0,
        },
        to: {
          x: -4.607544,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
  },
  {
    schemaVersion: 1,
    id: "port-filled",
    name: "Filled Port",
    viewBox: {
      x: -14,
      y: -7,
      width: 28,
      height: 14,
    },
    pins: [
      {
        name: "P",
        role: "port",
        at: {
          x: 10,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "circle",
        center: {
          x: -7.086614,
          y: 0,
        },
        radius: 2.47907,
        fill: "foreground",
        stroke: "foreground",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 10,
          y: 0,
        },
        to: {
          x: -4.607544,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
  },
  {
    schemaVersion: 1,
    id: "resistor",
    name: "Resistor",
    viewBox: {
      x: -10,
      y: -24,
      width: 20,
      height: 48,
    },
    pins: [
      {
        name: "1",
        role: "passive",
        at: {
          x: 0,
          y: -20,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "2",
        role: "passive",
        at: {
          x: 0,
          y: 20,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "path",
        data: "M 0 -20 L 0 -8.72093 L 5.372093 -6.395349 L -4.604651 -4.069767 L 5.372093 -1.162791 L -4.988372 1.744186 L 5.372093 4.651163 L -4.604651 7.55814 L 0 8.72093 L 0 20",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
          miterLimit: 12,
        },
      },
    ],
    variants: [],
  },
  {
    schemaVersion: 1,
    id: "voltage-amplifier",
    name: "Voltage Amplifier",
    viewBox: {
      x: -44,
      y: -28,
      width: 88,
      height: 56,
    },
    pins: [
      {
        name: "IN",
        role: "input",
        at: {
          x: -40,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 20,
        },
      },
      {
        name: "OUT",
        role: "output",
        at: {
          x: 40,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 20,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -40,
          y: 0,
        },
        to: {
          x: -23.63,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "path",
        data: "M -23.63 -28.62 L -23.63 28.62 L 23.63 0 Z",
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 23.63,
          y: 0,
        },
        to: {
          x: 40,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
  },
  {
    schemaVersion: 1,
    id: "voltage-source",
    name: "Independent Voltage Source",
    viewBox: {
      x: -24,
      y: -24,
      width: 39,
      height: 48,
    },
    pins: [
      {
        name: "+",
        role: "positive",
        at: {
          x: 0,
          y: -20,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "-",
        role: "negative",
        at: {
          x: 0,
          y: 20,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "circle",
        center: {
          x: 0,
          y: 0,
        },
        radius: 10.755814,
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -20.058139,
          y: -14.534884,
        },
        to: {
          x: -11.918605,
          y: -14.534884,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -15.988372,
          y: -18.604651,
        },
        to: {
          x: -15.988372,
          y: -10.465117,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -20.058139,
          y: 13.372093,
        },
        to: {
          x: -11.918605,
          y: 13.372093,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: -10.755814,
        },
        to: {
          x: 0,
          y: -20,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: 10.755814,
        },
        to: {
          x: 0,
          y: 20,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
  },
];
