import type { DeviceParameterDefinition } from "../contract.js";

/** One authoring contract shared by ordinary independent voltage/current sources. */
export function independentSourceParameters(
  unit: "V" | "A",
  dcPlaceholder: string,
): readonly DeviceParameterDefinition[] {
  const signalPlaceholder = unit === "V" ? "1" : "1m";
  return [
    {
      name: "dc",
      label: "DC value",
      required: true,
      editor: "text",
      unitHint: unit,
      placeholder: dcPlaceholder,
      help: "DC value and operating-point bias",
      displayRole: "value",
    },
    {
      name: "waveform",
      label: "Waveform",
      required: false,
      editor: "select",
      options: [
        { value: "dc", label: "DC" },
        { value: "pulse", label: "PULSE" },
        { value: "sin", label: "SIN" },
      ],
      placeholder: "dc",
      help: "Transient waveform emitted by this source",
      defaultValue: "dc",
      displayRole: "none",
    },
    {
      name: "acMagnitude",
      label: "AC magnitude",
      required: false,
      editor: "text",
      unitHint: unit,
      placeholder: signalPlaceholder,
      help: "Small-signal magnitude for AC analysis; leave empty for no AC excitation",
      displayRole: "none",
    },
    {
      name: "acPhase",
      label: "AC phase",
      required: false,
      editor: "text",
      unitHint: "deg",
      placeholder: "0",
      help: "Small-signal phase in degrees; used only with an AC magnitude",
      displayRole: "none",
    },
    {
      name: "low",
      label: "Low",
      required: false,
      editor: "text",
      unitHint: unit,
      placeholder: "0",
      help: "PULSE value before and between active pulses",
      defaultValue: "0",
      visibleForSourceWaveforms: ["pulse"],
      displayRole: "none",
    },
    {
      name: "high",
      label: "High",
      required: false,
      editor: "text",
      unitHint: unit,
      placeholder: signalPlaceholder,
      help: "PULSE active value",
      defaultValue: signalPlaceholder,
      visibleForSourceWaveforms: ["pulse"],
      displayRole: "none",
    },
    {
      name: "delay",
      label: "Delay",
      required: false,
      editor: "text",
      unitHint: "s",
      placeholder: "0",
      help: "Time before the transient waveform begins",
      defaultValue: "0",
      visibleForSourceWaveforms: ["pulse", "sin"],
      displayRole: "none",
    },
    {
      name: "rise",
      label: "Rise time",
      required: false,
      editor: "text",
      unitHint: "s",
      placeholder: "1ps",
      help: "PULSE rising-edge duration",
      defaultValue: "1ps",
      visibleForSourceWaveforms: ["pulse"],
      displayRole: "none",
    },
    {
      name: "fall",
      label: "Fall time",
      required: false,
      editor: "text",
      unitHint: "s",
      placeholder: "1ps",
      help: "PULSE falling-edge duration",
      defaultValue: "1ps",
      visibleForSourceWaveforms: ["pulse"],
      displayRole: "none",
    },
    {
      name: "width",
      label: "Pulse width",
      required: false,
      editor: "text",
      unitHint: "s",
      placeholder: "5ns",
      help: "Time the PULSE source remains at its high value",
      defaultValue: "5ns",
      visibleForSourceWaveforms: ["pulse"],
      displayRole: "none",
    },
    {
      name: "period",
      label: "Period",
      required: false,
      editor: "text",
      unitHint: "s",
      placeholder: "10ns",
      help: "Time between PULSE rising edges",
      defaultValue: "10ns",
      visibleForSourceWaveforms: ["pulse"],
      displayRole: "none",
    },
    {
      name: "offset",
      label: "Offset",
      required: false,
      editor: "text",
      unitHint: unit,
      placeholder: "0",
      help: "SIN waveform offset",
      defaultValue: "0",
      visibleForSourceWaveforms: ["sin"],
      displayRole: "none",
    },
    {
      name: "amplitude",
      label: "Amplitude",
      required: false,
      editor: "text",
      unitHint: unit,
      placeholder: signalPlaceholder,
      help: "SIN peak amplitude",
      defaultValue: signalPlaceholder,
      visibleForSourceWaveforms: ["sin"],
      displayRole: "none",
    },
    {
      name: "frequency",
      label: "Frequency",
      required: false,
      editor: "text",
      unitHint: "Hz",
      placeholder: "1k",
      help: "SIN frequency",
      defaultValue: "1k",
      visibleForSourceWaveforms: ["sin"],
      displayRole: "none",
    },
    {
      name: "damping",
      label: "Damping",
      required: false,
      editor: "text",
      unitHint: "1/s",
      placeholder: "0",
      help: "SIN exponential damping factor",
      defaultValue: "0",
      visibleForSourceWaveforms: ["sin"],
      displayRole: "none",
    },
    {
      name: "phase",
      label: "SIN phase",
      required: false,
      editor: "text",
      unitHint: "deg",
      placeholder: "0",
      help: "SIN phase in degrees",
      defaultValue: "0",
      visibleForSourceWaveforms: ["sin"],
      displayRole: "none",
    },
  ];
}
