import type { DeviceDescriptor } from "../contract.js";

export const pulseVoltageSourceDevice = {
  id: "pulse-voltage-source",
  symbolId: "pulse-voltage-source",
  deviceClass: "voltage-source",
  referencePrefix: "V",
  pinOrder: ["+", "-"],
  targetPolicy: "builtin",
  parameters: [
    {
      name: "period",
      label: "Period",
      required: true,
      editor: "text",
      unitHint: "s",
      placeholder: "10ns",
      help: "Time for one complete clock cycle",
      defaultValue: "10ns",
      displayRole: "value",
    },
    {
      name: "dutyCycle",
      label: "Duty cycle",
      required: false,
      editor: "decimal",
      unitHint: "%",
      placeholder: "50",
      help: "Percentage of each period at logic 1",
      defaultValue: "50",
      displayRole: "none",
    },
    {
      name: "initial",
      label: "Initial level",
      required: false,
      editor: "decimal",
      placeholder: "0",
      help: "Logic level at the start of simulation (0 or 1)",
      defaultValue: "0",
      displayRole: "none",
    },
    {
      name: "low",
      label: "Low",
      required: true,
      editor: "text",
      unitHint: "V",
      placeholder: "0",
      help: "Voltage while the pulse is low",
      defaultValue: "0",
      displayRole: "none",
      authoringVisibility: "compatibility",
    },
    {
      name: "high",
      label: "High",
      required: true,
      editor: "text",
      unitHint: "V",
      placeholder: "1",
      help: "Voltage while the pulse is high",
      defaultValue: "1",
      displayRole: "none",
      authoringVisibility: "compatibility",
    },
    {
      name: "delay",
      label: "Delay",
      required: true,
      editor: "text",
      unitHint: "s",
      placeholder: "5ns",
      help: "SPICE-compatible time before the first active edge",
      defaultValue: "5ns",
      displayRole: "none",
      authoringVisibility: "compatibility",
    },
    {
      name: "rise",
      label: "Rise",
      required: true,
      editor: "text",
      unitHint: "s",
      placeholder: "1ps",
      help: "Analog netlist rise time",
      defaultValue: "1ps",
      displayRole: "none",
      authoringVisibility: "compatibility",
    },
    {
      name: "fall",
      label: "Fall",
      required: true,
      editor: "text",
      unitHint: "s",
      placeholder: "1ps",
      help: "Analog netlist fall time",
      defaultValue: "1ps",
      displayRole: "none",
      authoringVisibility: "compatibility",
    },
    {
      name: "width",
      label: "Width",
      required: true,
      editor: "text",
      unitHint: "s",
      placeholder: "5ns",
      help: "Time the pulse remains high",
      defaultValue: "5ns",
      displayRole: "none",
      authoringVisibility: "compatibility",
    },
  ],
  dialects: ["spice", "spectre"],
  capabilities: {
    supportsModel: false,
    supportsBulkBinding: false,
    supportsValueAnnotation: true,
  },
} satisfies DeviceDescriptor;
