// The commands a formula may use: symbols, operators, accents, delimiters,
// environments, spaces and styles, and the letters of each math alphabet.
import { GREEK_LETTERS } from "@icm/model";

import type {
  Align,
  Alphabet,
  AtomClass,
  Style,
} from "./label-formula-nodes.js";

/**
 * Greek letters as the label editor spells them, so `\phi` is the same φ in
 * a formula as in a label. The variant commands have no label spelling of
 * their own; each takes its Unicode variant, or the label's letter where
 * that is the same letter.
 */
export const GREEK: Record<string, string> = {
  ...Object.fromEntries(
    GREEK_LETTERS.filter(({ latex }) => latex).map(({ name, glyph }) => [
      name,
      glyph,
    ]),
  ),
  varepsilon: "ε",
  vartheta: "ϑ",
  varpi: "ϖ",
  varrho: "ϱ",
  varsigma: "ς",
  varphi: "φ",
  varkappa: "ϰ",
  digamma: "ϝ",
};

export const SYMBOLS: Record<string, [string, AtomClass]> = {
  pm: ["±", "bin"],
  mp: ["∓", "bin"],
  times: ["×", "bin"],
  cdot: ["·", "bin"],
  cdotp: ["·", "punct"],
  div: ["÷", "bin"],
  ast: ["∗", "bin"],
  star: ["⋆", "bin"],
  circ: ["∘", "bin"],
  bullet: ["•", "bin"],
  oplus: ["⊕", "bin"],
  ominus: ["⊖", "bin"],
  otimes: ["⊗", "bin"],
  oslash: ["⊘", "bin"],
  odot: ["⊙", "bin"],
  cup: ["∪", "bin"],
  cap: ["∩", "bin"],
  sqcup: ["⊔", "bin"],
  sqcap: ["⊓", "bin"],
  uplus: ["⊎", "bin"],
  amalg: ["⨿", "bin"],
  wedge: ["∧", "bin"],
  land: ["∧", "bin"],
  vee: ["∨", "bin"],
  lor: ["∨", "bin"],
  setminus: ["∖", "bin"],
  wr: ["≀", "bin"],
  diamond: ["⋄", "bin"],
  bigtriangleup: ["△", "bin"],
  bigtriangledown: ["▽", "bin"],
  triangleleft: ["◁", "bin"],
  triangleright: ["▷", "bin"],
  dagger: ["†", "bin"],
  ddagger: ["‡", "bin"],
  leq: ["≤", "rel"],
  le: ["≤", "rel"],
  leqslant: ["⩽", "rel"],
  geq: ["≥", "rel"],
  ge: ["≥", "rel"],
  geqslant: ["⩾", "rel"],
  neq: ["≠", "rel"],
  ne: ["≠", "rel"],
  approx: ["≈", "rel"],
  approxeq: ["≊", "rel"],
  equiv: ["≡", "rel"],
  sim: ["∼", "rel"],
  simeq: ["≃", "rel"],
  cong: ["≅", "rel"],
  asymp: ["≍", "rel"],
  doteq: ["≐", "rel"],
  triangleq: ["≜", "rel"],
  coloneqq: ["≔", "rel"],
  lesssim: ["≲", "rel"],
  gtrsim: ["≳", "rel"],
  prec: ["≺", "rel"],
  succ: ["≻", "rel"],
  preceq: ["⪯", "rel"],
  succeq: ["⪰", "rel"],
  propto: ["∝", "rel"],
  varpropto: ["∝", "rel"],
  // The label fonts lack ∥ and ∣; the double and single bars they have read
  // the same.
  parallel: ["‖", "rel"],
  nparallel: ["∦", "rel"],
  to: ["→", "rel"],
  rightarrow: ["→", "rel"],
  leftarrow: ["←", "rel"],
  gets: ["←", "rel"],
  leftrightarrow: ["↔", "rel"],
  longrightarrow: ["⟶", "rel"],
  longleftarrow: ["⟵", "rel"],
  longleftrightarrow: ["⟷", "rel"],
  Rightarrow: ["⇒", "rel"],
  Leftarrow: ["⇐", "rel"],
  Leftrightarrow: ["⇔", "rel"],
  Longrightarrow: ["⟹", "rel"],
  Longleftarrow: ["⟸", "rel"],
  Longleftrightarrow: ["⟺", "rel"],
  implies: ["⟹", "rel"],
  impliedby: ["⟸", "rel"],
  iff: ["⟺", "rel"],
  mapsto: ["↦", "rel"],
  longmapsto: ["⟼", "rel"],
  hookrightarrow: ["↪", "rel"],
  hookleftarrow: ["↩", "rel"],
  uparrow: ["↑", "rel"],
  downarrow: ["↓", "rel"],
  updownarrow: ["↕", "rel"],
  Uparrow: ["⇑", "rel"],
  Downarrow: ["⇓", "rel"],
  Updownarrow: ["⇕", "rel"],
  nearrow: ["↗", "rel"],
  searrow: ["↘", "rel"],
  swarrow: ["↙", "rel"],
  nwarrow: ["↖", "rel"],
  rightleftharpoons: ["⇌", "rel"],
  leftrightharpoons: ["⇋", "rel"],
  rightharpoonup: ["⇀", "rel"],
  leftharpoonup: ["↼", "rel"],
  ll: ["≪", "rel"],
  gg: ["≫", "rel"],
  in: ["∈", "rel"],
  notin: ["∉", "rel"],
  ni: ["∋", "rel"],
  owns: ["∋", "rel"],
  subset: ["⊂", "rel"],
  supset: ["⊃", "rel"],
  subseteq: ["⊆", "rel"],
  supseteq: ["⊇", "rel"],
  subsetneq: ["⊊", "rel"],
  supsetneq: ["⊋", "rel"],
  sqsubseteq: ["⊑", "rel"],
  sqsupseteq: ["⊒", "rel"],
  perp: ["⊥", "rel"],
  mid: ["|", "rel"],
  nmid: ["∤", "rel"],
  vdash: ["⊢", "rel"],
  dashv: ["⊣", "rel"],
  models: ["⊨", "rel"],
  bowtie: ["⋈", "rel"],
  Join: ["⋈", "rel"],
  smile: ["⌣", "rel"],
  frown: ["⌢", "rel"],
  nleq: ["≰", "rel"],
  ngeq: ["≱", "rel"],
  nless: ["≮", "rel"],
  ngtr: ["≯", "rel"],
  nsim: ["≁", "rel"],
  ncong: ["≇", "rel"],
  nequiv: ["≢", "rel"],
  colon: [":", "punct"],
  infty: ["∞", "ord"],
  partial: ["∂", "ord"],
  nabla: ["∇", "ord"],
  degree: ["°", "ord"],
  circledast: ["⊛", "ord"],
  prime: ["′", "ord"],
  ldots: ["…", "ord"],
  cdots: ["⋯", "ord"],
  dots: ["…", "ord"],
  dotsc: ["…", "ord"],
  dotsb: ["⋯", "ord"],
  vdots: ["⋮", "ord"],
  ddots: ["⋱", "ord"],
  forall: ["∀", "ord"],
  exists: ["∃", "ord"],
  nexists: ["∄", "ord"],
  emptyset: ["∅", "ord"],
  varnothing: ["∅", "ord"],
  neg: ["¬", "ord"],
  lnot: ["¬", "ord"],
  angle: ["∠", "ord"],
  measuredangle: ["∡", "ord"],
  sphericalangle: ["∢", "ord"],
  triangle: ["△", "ord"],
  square: ["□", "ord"],
  Box: ["□", "ord"],
  blacksquare: ["■", "ord"],
  Diamond: ["◇", "ord"],
  bigstar: ["★", "ord"],
  checkmark: ["✓", "ord"],
  top: ["⊤", "ord"],
  bot: ["⊥", "ord"],
  therefore: ["∴", "rel"],
  because: ["∵", "rel"],
  hbar: ["ℏ", "ord"],
  hslash: ["ℏ", "ord"],
  ell: ["ℓ", "ord"],
  wp: ["℘", "ord"],
  Re: ["ℜ", "ord"],
  Im: ["ℑ", "ord"],
  aleph: ["ℵ", "ord"],
  beth: ["ℶ", "ord"],
  mho: ["℧", "ord"],
  imath: ["ı", "ord"],
  jmath: ["ȷ", "ord"],
  sharp: ["♯", "ord"],
  flat: ["♭", "ord"],
  natural: ["♮", "ord"],
  S: ["§", "ord"],
  P: ["¶", "ord"],
  dag: ["†", "ord"],
  ddag: ["‡", "ord"],
  pounds: ["£", "ord"],
  copyright: ["©", "ord"],
  backslash: ["\\", "ord"],
  vert: ["|", "ord"],
  Vert: ["‖", "ord"],
  langle: ["⟨", "open"],
  rangle: ["⟩", "close"],
  lceil: ["⌈", "open"],
  rceil: ["⌉", "close"],
  lfloor: ["⌊", "open"],
  rfloor: ["⌋", "close"],
  lvert: ["|", "open"],
  rvert: ["|", "close"],
  lVert: ["‖", "open"],
  rVert: ["‖", "close"],
  lbrace: ["{", "open"],
  rbrace: ["}", "close"],
  lbrack: ["[", "open"],
  rbrack: ["]", "close"],
};

/** A relation struck through by \not, as its own Unicode character. */
export const NEGATIONS: Record<string, string> = {
  "=": "≠",
  "<": "≮",
  ">": "≯",
  "\\in": "∉",
  "\\ni": "∌",
  "\\subset": "⊄",
  "\\supset": "⊅",
  "\\subseteq": "⊈",
  "\\supseteq": "⊉",
  "\\equiv": "≢",
  "\\sim": "≁",
  "\\approx": "≉",
  "\\cong": "≇",
  "\\simeq": "≄",
  "\\leq": "≰",
  "\\le": "≰",
  "\\geq": "≱",
  "\\ge": "≱",
  "\\parallel": "∦",
  "\\mid": "∤",
  "\\prec": "⊀",
  "\\succ": "⊁",
};

/** Operator names, upright; the second marks limits above and below. */
export const FUNCTIONS: Record<string, [string, boolean]> = {
  sin: ["sin", false],
  cos: ["cos", false],
  tan: ["tan", false],
  cot: ["cot", false],
  sec: ["sec", false],
  csc: ["csc", false],
  sinh: ["sinh", false],
  cosh: ["cosh", false],
  tanh: ["tanh", false],
  coth: ["coth", false],
  arcsin: ["arcsin", false],
  arccos: ["arccos", false],
  arctan: ["arctan", false],
  log: ["log", false],
  ln: ["ln", false],
  lg: ["lg", false],
  exp: ["exp", false],
  dim: ["dim", false],
  ker: ["ker", false],
  hom: ["hom", false],
  arg: ["arg", false],
  deg: ["deg", false],
  det: ["det", true],
  gcd: ["gcd", true],
  max: ["max", true],
  min: ["min", true],
  sup: ["sup", true],
  inf: ["inf", true],
  lim: ["lim", true],
  liminf: ["lim inf", true],
  limsup: ["lim sup", true],
  Pr: ["Pr", true],
};

/** Large operators: a sum's limits stack in display style, an integral's do not. */
export const LARGE_OPERATORS: Record<string, [string, "sum" | "integral"]> = {
  sum: ["∑", "sum"],
  prod: ["∏", "sum"],
  coprod: ["∐", "sum"],
  bigcup: ["⋃", "sum"],
  bigcap: ["⋂", "sum"],
  bigoplus: ["⨁", "sum"],
  bigotimes: ["⨂", "sum"],
  bigodot: ["⨀", "sum"],
  biguplus: ["⨄", "sum"],
  bigsqcup: ["⨆", "sum"],
  bigvee: ["⋁", "sum"],
  bigwedge: ["⋀", "sum"],
  int: ["∫", "integral"],
  iint: ["∬", "integral"],
  iiint: ["∭", "integral"],
  oint: ["∮", "integral"],
  oiint: ["∯", "integral"],
};

export const ACCENTS: Record<
  string,
  { mark: string; wide?: boolean; arrow?: boolean }
> = {
  hat: { mark: "ˆ" },
  check: { mark: "ˇ" },
  tilde: { mark: "˜" },
  acute: { mark: "´" },
  grave: { mark: "`" },
  dot: { mark: "˙" },
  ddot: { mark: "¨" },
  breve: { mark: "˘" },
  mathring: { mark: "˚" },
  vec: { mark: "→", arrow: true },
  widehat: { mark: "ˆ", wide: true },
  widetilde: { mark: "˜", wide: true },
  widecheck: { mark: "ˇ", wide: true },
  overrightarrow: { mark: "→", wide: true, arrow: true },
  overleftarrow: { mark: "←", wide: true, arrow: true },
  overleftrightarrow: { mark: "↔", wide: true, arrow: true },
};

/** \big and its kin: height in em, and the class a suffix gives. */
export const BIG_DELIMITERS: Record<string, [number, AtomClass | null]> = {
  big: [1.2, null],
  Big: [1.8, null],
  bigg: [2.4, null],
  Bigg: [3, null],
  bigl: [1.2, "open"],
  Bigl: [1.8, "open"],
  biggl: [2.4, "open"],
  Biggl: [3, "open"],
  bigr: [1.2, "close"],
  Bigr: [1.8, "close"],
  biggr: [2.4, "close"],
  Biggr: [3, "close"],
  bigm: [1.2, "rel"],
  Bigm: [1.8, "rel"],
  biggm: [2.4, "rel"],
  Biggm: [3, "rel"],
};

export const ENVIRONMENTS: Record<
  string,
  {
    left?: string;
    right?: string;
    align: Align | "rl" | "spec";
    cellStyle: Style;
    gaps: "matrix" | "cases" | "aligned";
  }
> = {
  matrix: { align: "c", cellStyle: 1, gaps: "matrix" },
  pmatrix: { left: "(", right: ")", align: "c", cellStyle: 1, gaps: "matrix" },
  bmatrix: { left: "[", right: "]", align: "c", cellStyle: 1, gaps: "matrix" },
  Bmatrix: { left: "{", right: "}", align: "c", cellStyle: 1, gaps: "matrix" },
  vmatrix: { left: "|", right: "|", align: "c", cellStyle: 1, gaps: "matrix" },
  Vmatrix: { left: "‖", right: "‖", align: "c", cellStyle: 1, gaps: "matrix" },
  smallmatrix: { align: "c", cellStyle: 2, gaps: "matrix" },
  cases: { left: "{", align: "l", cellStyle: 1, gaps: "cases" },
  dcases: { left: "{", align: "l", cellStyle: 0, gaps: "cases" },
  rcases: { right: "}", align: "l", cellStyle: 1, gaps: "cases" },
  aligned: { align: "rl", cellStyle: 0, gaps: "aligned" },
  align: { align: "rl", cellStyle: 0, gaps: "aligned" },
  "align*": { align: "rl", cellStyle: 0, gaps: "aligned" },
  split: { align: "rl", cellStyle: 0, gaps: "aligned" },
  gathered: { align: "c", cellStyle: 0, gaps: "matrix" },
  gather: { align: "c", cellStyle: 0, gaps: "matrix" },
  "gather*": { align: "c", cellStyle: 0, gaps: "matrix" },
  array: { align: "spec", cellStyle: 1, gaps: "matrix" },
};

export const SPACES: Record<string, number> = {
  ",": 1 / 6,
  ":": 2 / 9,
  ">": 2 / 9,
  ";": 5 / 18,
  "!": -1 / 6,
  quad: 1,
  qquad: 2,
  enspace: 0.5,
  thinspace: 1 / 6,
  medspace: 2 / 9,
  thickspace: 5 / 18,
  negthinspace: -1 / 6,
  negmedspace: -2 / 9,
  negthickspace: -5 / 18,
  " ": 0.318,
};

export const IGNORED = new Set([
  "nonumber",
  "notag",
  "allowbreak",
  "nobreak",
  "relax",
  "displaylimits",
]);

export const STYLES: Record<string, Style> = {
  displaystyle: 0,
  textstyle: 1,
  scriptstyle: 2,
  scriptscriptstyle: 3,
};

/** Letters of \mathbb, \mathcal, \mathfrak whose Unicode form is in the BMP. */
const LETTERLIKE: Record<Exclude<Alphabet, "mono">, Record<string, string>> = {
  double: { C: "ℂ", H: "ℍ", N: "ℕ", P: "ℙ", Q: "ℚ", R: "ℝ", Z: "ℤ" },
  script: {
    B: "ℬ",
    E: "ℰ",
    F: "ℱ",
    H: "ℋ",
    I: "ℐ",
    L: "ℒ",
    M: "ℳ",
    R: "ℛ",
    e: "ℯ",
    g: "ℊ",
    o: "ℴ",
  },
  fraktur: { C: "ℭ", H: "ℌ", I: "ℑ", R: "ℜ", Z: "ℨ" },
};
/** First code point of each alphabet's capitals, small letters and digits. */
const ALPHABET_STARTS: Record<
  Exclude<Alphabet, "mono">,
  [number, number, number | null]
> = {
  double: [0x1d538, 0x1d552, 0x1d7d8],
  script: [0x1d49c, 0x1d4b6, null],
  fraktur: [0x1d504, 0x1d51e, null],
};

export function alphabetCharacter(char: string, alphabet: Alphabet): string {
  if (alphabet === "mono") return char;
  const letterlike = LETTERLIKE[alphabet][char];
  if (letterlike) return letterlike;
  const [capitals, smalls, digits] = ALPHABET_STARTS[alphabet];
  const code = char.codePointAt(0)!;
  if (char >= "A" && char <= "Z")
    return String.fromCodePoint(capitals + code - 65);
  if (char >= "a" && char <= "z")
    return String.fromCodePoint(smalls + code - 97);
  if (digits !== null && char >= "0" && char <= "9")
    return String.fromCodePoint(digits + code - 48);
  return char;
}
