// Generated by scripts/generate-agent-docs.mjs. Edit docs/agent sources, not this output.
export const agentApiHelp = {
  agentSessionStatus:
    "Read authenticated relay observations without contacting the editor or renewing the idle deadline. Attachment is not execution readiness. Paused sessions remain readable.",
  agentClaimRedeem:
    "Exchange a human-provided claim for authorized Document IDs, a scoped bearer and a revocable connector. Repeating a valid claim rotates credentials and invalidates the earlier pairing.",
  agentConnectorResume:
    "Exchange a server-issued persistent connector credential for a fresh short-lived Circuit bearer. The connector remains revocable with its browser session.",
  agentSessionCircuit:
    "Send one Circuit API request over the session. The relay validates the strict payload and required token scopes, then forwards it to the live browser without applying or rewriting edits.",
  agentSessionFileResource:
    "Export Project/SVG/PNG/PDF; stage and inspect import candidates; read/update simulation source or retrieve immutable run artifacts. Staging alone never replaces the Project: browser-human confirmation is required. Source updates use their owner's revision. replacements accepts path/textDigest/oldText/newText, requires one exact match against original text, and commits atomically with writes/removes/patches. Success returns source.revision and update with changed files, new digests and byte lengths; no-op saves do not advance revision. Listings advertise editing modes; fileEdit errors locate rejected edits with applied:false. Artifact access does not grant arbitrary host files.",
  agentSessionSimulationResource:
    "Discover Profiles and native authoring help; prepare saved Project-folder or session-workspace source, then start/read/catalog/cancel/export runs and batches. history lists retained completed runs with limit/cursor pagination and storage status; reconnect to the same Project then read catalog or download its files, without restarting. Catalog returns file roles, datasets, axes, units and representation selectors without samples. Exact start request-ID and payload retries do not execute twice. Download full artifacts for local analysis. Input/execution failures do not revoke the session; this is not a durable job queue.",
  agentSessionProjectResource:
    "Page through the public Gallery, read complete Gallery Project Code and generated netlists, read or replace the open Project Code and editable netlist fields, and discover/import Cells from signed-in Cloud Projects through the live editor transaction boundary.",
  agentSessionArtifactDownload:
    "Download immutable simulation bytes with the existing simulation.run bearer. Obtain the path from File simulation-input action download; ARTIFACT_TRANSFER_PENDING means publication continues in the background: wait retryAfterMs, then query with a new request ID, never restart the simulation. Text action artifact remains a preview. Stream to local disk; Range and If-Range support byte-resume. No browser Cookie or bearer in URLs. A registered transfer remains downloadable while its session is authorized even if the browser is temporarily offline. Session transfer replicas are removed on revocation or expiry; downloaded local files are independent.",
};
