// Generated by scripts/generate-agent-docs.mjs. Edit docs/agent sources, not this output.
export const agentApiHelp = {
  agentSessionStatus:
    "Read authenticated relay observations without contacting the editor or renewing the idle deadline. Attachment is not execution readiness. Paused sessions remain readable.",
  agentClaimRedeem:
    "Exchange a human-provided claim for authorized Document IDs, a scoped bearer and a revocable connector. Repeating a valid claim rotates credentials and invalidates the earlier pairing.",
  agentConnectorResume:
    "Exchange a server-issued persistent connector credential for a fresh short-lived Circuit bearer. The connector remains revocable with its browser session.",
  agentSessionCircuit:
    "Send one Circuit API request over the session. The relay validates the strict payload and required token scopes, then forwards it to the live browser without applying or rewriting edits.",
  agentSessionFileResource:
    "Export Project/Canvas files, stage imports, or access simulation source/evidence. Staging requires browser-human confirmation before replacement. Source updates are atomic and revisioned; receipts report paths/digests, and fileEdit locates rejected edits. Artifact access never grants arbitrary host files.",
  agentSessionSimulationResource:
    "Discover Profiles/help; run submits a revisioned source once, including preparation. Optional prepare/start supports inspection and reuse. Read/cancel or catalog/export runs and batches; history discovers retained evidence. Preserve request ID/payload for uncertain submissions, including during preparation. Execution failure does not revoke authorization.",
  agentSessionProjectResource:
    "Page through the public Gallery, read complete Gallery Project Code and generated netlists, read or replace the open Project Code and editable netlist fields, and discover/import Cells from signed-in Cloud Projects through the live editor transaction boundary.",
  agentSessionArtifactDownload:
    "Stream immutable bytes using the simulation.run bearer. Get paths via File simulation-input download or downloads (1–32 IDs); each batch entry independently reports ready/pending/error. Retry pending descriptors with fresh IDs after retryAfterMs, never restart execution. Range/If-Range support resume. No cookies or tokens in URLs. Authorized published transfers survive temporary browser offline; local files survive revocation.",
};
